name: CI/CD Pipeline

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This line is important for getting all history for all branches and tags

      - name: Generate version number
        id: version
        run: |
          echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/dockerreact:${{ steps.version.outputs.VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/dockerreact:${{ steps.version.outputs.VERSION }}

      - name: Update deployment file
        run: |
          sed -i 's|image: .*|image: ${{ secrets.DOCKER_USER_NAME }}/dockerreact:${{ steps.version.outputs.VERSION }}|' k8s/deployment.yaml

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Bump version to ${{ steps.version.outputs.VERSION }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}
